[2022-08-10 01:45:15,617] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: trigger_rule_dag.task_3 scheduled__2022-08-09T00:00:00+00:00 [queued]>
[2022-08-10 01:45:15,649] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: trigger_rule_dag.task_3 scheduled__2022-08-09T00:00:00+00:00 [queued]>
[2022-08-10 01:45:15,651] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-08-10 01:45:15,653] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-08-10 01:45:15,655] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-08-10 01:45:15,749] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): task_3> on 2022-08-09 00:00:00+00:00
[2022-08-10 01:45:15,766] {standard_task_runner.py:52} INFO - Started process 101 to run task
[2022-08-10 01:45:15,784] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'trigger_rule_dag', 'task_3', 'scheduled__2022-08-09T00:00:00+00:00', '--job-id', '325', '--raw', '--subdir', 'DAGS_FOLDER/trigger_rule_dag.py', '--cfg-path', '/tmp/tmpc8bm31t1', '--error-file', '/tmp/tmpel_7r88m']
[2022-08-10 01:45:15,791] {standard_task_runner.py:80} INFO - Job 325: Subtask task_3
[2022-08-10 01:45:16,014] {task_command.py:369} INFO - Running <TaskInstance: trigger_rule_dag.task_3 scheduled__2022-08-09T00:00:00+00:00 [running]> on host 531c07ae0142
[2022-08-10 01:45:16,549] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=trigger_rule_dag
AIRFLOW_CTX_TASK_ID=task_3
AIRFLOW_CTX_EXECUTION_DATE=2022-08-09T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-08-09T00:00:00+00:00
[2022-08-10 01:45:16,571] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-08-10 01:45:16,612] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'exit 0']
[2022-08-10 01:45:16,935] {subprocess.py:85} INFO - Output:
[2022-08-10 01:45:17,134] {subprocess.py:96} INFO - Command exited with return code 0
[2022-08-10 01:45:17,458] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=trigger_rule_dag, task_id=task_3, execution_date=20220809T000000, start_date=20220810T014515, end_date=20220810T014517
[2022-08-10 01:45:17,700] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-08-10 01:45:18,226] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
