[2022-08-12 00:59:10,069] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: trigger_rule_dag.task_3 scheduled__2022-08-11T00:00:00+00:00 [queued]>
[2022-08-12 00:59:10,081] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: trigger_rule_dag.task_3 scheduled__2022-08-11T00:00:00+00:00 [queued]>
[2022-08-12 00:59:10,082] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-08-12 00:59:10,083] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-08-12 00:59:10,083] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-08-12 00:59:10,104] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): task_3> on 2022-08-11 00:00:00+00:00
[2022-08-12 00:59:10,110] {standard_task_runner.py:52} INFO - Started process 3843 to run task
[2022-08-12 00:59:10,114] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'trigger_rule_dag', 'task_3', 'scheduled__2022-08-11T00:00:00+00:00', '--job-id', '366', '--raw', '--subdir', 'DAGS_FOLDER/trigger_rule_dag.py', '--cfg-path', '/tmp/tmp152bs0xq', '--error-file', '/tmp/tmpp5f6cjo8']
[2022-08-12 00:59:10,115] {standard_task_runner.py:80} INFO - Job 366: Subtask task_3
[2022-08-12 00:59:10,218] {task_command.py:369} INFO - Running <TaskInstance: trigger_rule_dag.task_3 scheduled__2022-08-11T00:00:00+00:00 [running]> on host c49533ed8cfb
[2022-08-12 00:59:10,331] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=trigger_rule_dag
AIRFLOW_CTX_TASK_ID=task_3
AIRFLOW_CTX_EXECUTION_DATE=2022-08-11T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-08-11T00:00:00+00:00
[2022-08-12 00:59:10,333] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-08-12 00:59:10,338] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'exit 0']
[2022-08-12 00:59:10,353] {subprocess.py:85} INFO - Output:
[2022-08-12 00:59:10,355] {subprocess.py:96} INFO - Command exited with return code 0
[2022-08-12 00:59:10,382] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=trigger_rule_dag, task_id=task_3, execution_date=20220811T000000, start_date=20220812T005910, end_date=20220812T005910
[2022-08-12 00:59:10,410] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-08-12 00:59:10,460] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
