[2022-08-05 00:03:52,756] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: trigger_rule_dag.task_3 scheduled__2022-08-04T00:00:00+00:00 [queued]>
[2022-08-05 00:03:52,770] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: trigger_rule_dag.task_3 scheduled__2022-08-04T00:00:00+00:00 [queued]>
[2022-08-05 00:03:52,771] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-08-05 00:03:52,772] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-08-05 00:03:52,772] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-08-05 00:03:52,790] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): task_3> on 2022-08-04 00:00:00+00:00
[2022-08-05 00:03:52,797] {standard_task_runner.py:52} INFO - Started process 78 to run task
[2022-08-05 00:03:52,802] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'trigger_rule_dag', 'task_3', 'scheduled__2022-08-04T00:00:00+00:00', '--job-id', '310', '--raw', '--subdir', 'DAGS_FOLDER/trigger_rule_dag.py', '--cfg-path', '/tmp/tmp3sfwu02x', '--error-file', '/tmp/tmp5gj8u5y8']
[2022-08-05 00:03:52,804] {standard_task_runner.py:80} INFO - Job 310: Subtask task_3
[2022-08-05 00:03:52,878] {task_command.py:369} INFO - Running <TaskInstance: trigger_rule_dag.task_3 scheduled__2022-08-04T00:00:00+00:00 [running]> on host 531c07ae0142
[2022-08-05 00:03:52,986] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=trigger_rule_dag
AIRFLOW_CTX_TASK_ID=task_3
AIRFLOW_CTX_EXECUTION_DATE=2022-08-04T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-08-04T00:00:00+00:00
[2022-08-05 00:03:52,988] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-08-05 00:03:52,989] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'exit 0']
[2022-08-05 00:03:53,003] {subprocess.py:85} INFO - Output:
[2022-08-05 00:03:53,005] {subprocess.py:96} INFO - Command exited with return code 0
[2022-08-05 00:03:53,028] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=trigger_rule_dag, task_id=task_3, execution_date=20220804T000000, start_date=20220805T000352, end_date=20220805T000353
[2022-08-05 00:03:53,100] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-08-05 00:03:53,151] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
