[2022-07-24 19:19:02,735] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: user_processing.is_api_available scheduled__2022-07-23T00:00:00+00:00 [queued]>
[2022-07-24 19:19:02,743] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: user_processing.is_api_available scheduled__2022-07-23T00:00:00+00:00 [queued]>
[2022-07-24 19:19:02,744] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-07-24 19:19:02,744] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-07-24 19:19:02,745] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-07-24 19:19:02,758] {taskinstance.py:1377} INFO - Executing <Task(HttpSensor): is_api_available> on 2022-07-23 00:00:00+00:00
[2022-07-24 19:19:02,763] {standard_task_runner.py:52} INFO - Started process 1022 to run task
[2022-07-24 19:19:02,767] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'user_processing', 'is_api_available', 'scheduled__2022-07-23T00:00:00+00:00', '--job-id', '101', '--raw', '--subdir', 'DAGS_FOLDER/user_processing.py', '--cfg-path', '/tmp/tmpdw9cspgi', '--error-file', '/tmp/tmp70kpxwfa']
[2022-07-24 19:19:02,768] {standard_task_runner.py:80} INFO - Job 101: Subtask is_api_available
[2022-07-24 19:19:02,827] {task_command.py:369} INFO - Running <TaskInstance: user_processing.is_api_available scheduled__2022-07-23T00:00:00+00:00 [running]> on host 8694d477c774
[2022-07-24 19:19:02,901] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=user_processing
AIRFLOW_CTX_TASK_ID=is_api_available
AIRFLOW_CTX_EXECUTION_DATE=2022-07-23T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-07-23T00:00:00+00:00
[2022-07-24 19:19:02,902] {http.py:97} INFO - Poking: api/
[2022-07-24 19:19:02,912] {base.py:68} INFO - Using connection ID 'user_api' for task execution.
[2022-07-24 19:19:02,914] {http.py:129} INFO - Sending 'GET' to url: https://randomuser.me/api/
[2022-07-24 19:19:03,970] {base.py:301} INFO - Success criteria met. Exiting.
[2022-07-24 19:19:03,986] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=user_processing, task_id=is_api_available, execution_date=20220723T000000, start_date=20220724T191902, end_date=20220724T191903
[2022-07-24 19:19:04,040] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-07-24 19:19:04,090] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
