[2022-08-14 13:49:07,163] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: trigger_rule_dag.task_3 scheduled__2022-08-12T00:00:00+00:00 [queued]>
[2022-08-14 13:49:07,335] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: trigger_rule_dag.task_3 scheduled__2022-08-12T00:00:00+00:00 [queued]>
[2022-08-14 13:49:07,350] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-08-14 13:49:07,354] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-08-14 13:49:07,358] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-08-14 13:49:07,572] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): task_3> on 2022-08-12 00:00:00+00:00
[2022-08-14 13:49:07,601] {standard_task_runner.py:52} INFO - Started process 9769 to run task
[2022-08-14 13:49:07,718] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'trigger_rule_dag', 'task_3', 'scheduled__2022-08-12T00:00:00+00:00', '--job-id', '402', '--raw', '--subdir', 'DAGS_FOLDER/trigger_rule_dag.py', '--cfg-path', '/tmp/tmp4i4s0tzd', '--error-file', '/tmp/tmp7w2tt3ql']
[2022-08-14 13:49:07,745] {standard_task_runner.py:80} INFO - Job 402: Subtask task_3
[2022-08-14 13:49:09,306] {task_command.py:369} INFO - Running <TaskInstance: trigger_rule_dag.task_3 scheduled__2022-08-12T00:00:00+00:00 [running]> on host a1c9528fe5e1
[2022-08-14 13:49:11,662] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=trigger_rule_dag
AIRFLOW_CTX_TASK_ID=task_3
AIRFLOW_CTX_EXECUTION_DATE=2022-08-12T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-08-12T00:00:00+00:00
[2022-08-14 13:49:11,675] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-08-14 13:49:11,686] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'exit 0']
[2022-08-14 13:49:11,776] {subprocess.py:85} INFO - Output:
[2022-08-14 13:49:11,782] {subprocess.py:96} INFO - Command exited with return code 0
[2022-08-14 13:49:11,930] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=trigger_rule_dag, task_id=task_3, execution_date=20220812T000000, start_date=20220814T134907, end_date=20220814T134911
[2022-08-14 13:49:12,516] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-08-14 13:49:12,961] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
