[2022-08-14 18:19:50,362] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: spark_job_dag.git_clone manual__2022-08-14T18:19:48.180562+00:00 [queued]>
[2022-08-14 18:19:50,372] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: spark_job_dag.git_clone manual__2022-08-14T18:19:48.180562+00:00 [queued]>
[2022-08-14 18:19:50,373] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-08-14 18:19:50,374] {taskinstance.py:1357} INFO - Starting attempt 1 of 2
[2022-08-14 18:19:50,374] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-08-14 18:19:50,387] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): git_clone> on 2022-08-14 18:19:48.180562+00:00
[2022-08-14 18:19:50,393] {standard_task_runner.py:52} INFO - Started process 3823 to run task
[2022-08-14 18:19:50,397] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'spark_job_dag', 'git_clone', 'manual__2022-08-14T18:19:48.180562+00:00', '--job-id', '449', '--raw', '--subdir', 'DAGS_FOLDER/spark_job_dag.py', '--cfg-path', '/tmp/tmps8qj9gfq', '--error-file', '/tmp/tmp15zpkkzx']
[2022-08-14 18:19:50,398] {standard_task_runner.py:80} INFO - Job 449: Subtask git_clone
[2022-08-14 18:19:50,458] {task_command.py:369} INFO - Running <TaskInstance: spark_job_dag.git_clone manual__2022-08-14T18:19:48.180562+00:00 [running]> on host 976456e83212
[2022-08-14 18:19:50,526] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=spark_job_dag
AIRFLOW_CTX_TASK_ID=git_clone
AIRFLOW_CTX_EXECUTION_DATE=2022-08-14T18:19:48.180562+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-08-14T18:19:48.180562+00:00
[2022-08-14 18:19:50,529] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-08-14 18:19:50,530] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'git clone https://github.com/marclamberti/simple-app.git /home/***/simple-app']
[2022-08-14 18:19:50,544] {subprocess.py:85} INFO - Output:
[2022-08-14 18:19:50,546] {subprocess.py:92} INFO - bash: line 1: git: command not found
[2022-08-14 18:19:50,547] {subprocess.py:96} INFO - Command exited with return code 127
[2022-08-14 18:19:50,561] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 195, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2022-08-14 18:19:50,565] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=spark_job_dag, task_id=git_clone, execution_date=20220814T181948, start_date=20220814T181950, end_date=20220814T181950
[2022-08-14 18:19:50,577] {standard_task_runner.py:97} ERROR - Failed to execute job 449 for task git_clone (Bash command failed. The command returned a non-zero exit code 127.; 3823)
[2022-08-14 18:19:50,611] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-08-14 18:19:50,655] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
